import { BlogPost, Branch, LoanTier, Testimonial, Vehicle } from './types';

const now = '2026-06-11T00:00:00.000Z';

// Static seed inventory. The app copies this into localStorage on first load so
// the admin prototype can create, edit, archive, and feature vehicles locally.
export const INVENTORY: Vehicle[] = [
  {
    id: 'v-001',
    slug: 'mercedes-benz-s-class-s580-2023',
    make: 'Mercedes-Benz',
    model: 'S-Class',
    trim: 'S 580 4MATIC',
    year: 2023,
    price: 18500000,
    mileage: 12000,
    fuel: 'Petrol Hybrid',
    transmission: 'Automatic',
    image: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?q=80&w=2543&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?q=80&w=2543&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=2670&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1616788494672-ec7ca25fdda9?q=80&w=2670&auto=format&fit=crop',
    ],
    bodyType: 'Sedan',
    engine: '4.0L V8 mild hybrid',
    seats: 5,
    driveType: 'All-Wheel Drive',
    color: 'Obsidian Black',
    condition: 'Foreign Used',
    availability: 'Available',
    location: 'Nairobi Showroom',
    vin: 'W1K6G7GB2PA001234',
    negotiable: true,
    featured: true,
    loanEligible: true,
    description: 'Executive flagship sedan with advanced comfort, digital cockpit technology, and a refined hybrid-assisted V8 drivetrain.',
    features: ['Burmester 3D Surround', 'MBUX AR Head-Up Display', 'Active Ambient Lighting', 'Rear Seat Entertainment', 'Air Suspension', '360 Camera'],
    createdAt: now,
  },
  {
    id: 'v-002',
    slug: 'range-rover-autobiography-2022',
    make: 'Range Rover',
    model: 'Autobiography',
    year: 2022,
    price: 24000000,
    mileage: 28000,
    fuel: 'Diesel',
    transmission: 'Automatic',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0b12?q=80&w=2670&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0b12?q=80&w=2670&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?q=80&w=2670&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1563720223185-11003d516935?q=80&w=2670&auto=format&fit=crop',
    ],
    bodyType: 'SUV',
    engine: '3.0L inline-six diesel',
    seats: 5,
    driveType: 'All-Wheel Drive',
    color: 'Santorini Black',
    condition: 'Foreign Used',
    availability: 'Available',
    location: 'Nairobi Showroom',
    vin: 'SALGS2RKXNA401234',
    negotiable: true,
    featured: true,
    loanEligible: true,
    description: 'Luxury SUV with executive ride quality, strong diesel torque, and premium cabin appointments for business or family use.',
    features: ['Meridian Signature Sound', 'Executive Comfort Seats', 'Pixel LED Headlights', 'Terrain Response', 'Panoramic Roof', 'Air Suspension'],
    createdAt: now,
  },
  {
    id: 'v-003',
    slug: 'porsche-taycan-4s-2024',
    make: 'Porsche',
    model: 'Taycan',
    trim: '4S',
    year: 2024,
    price: 16500000,
    mileage: 500,
    fuel: 'Electric',
    transmission: '2-Speed Automatic',
    image: 'https://images.unsplash.com/photo-1614027164847-1b28ce1bd374?q=80&w=2692&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1614027164847-1b28ce1bd374?q=80&w=2692&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?q=80&w=2670&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1614200187524-dc4b892acf16?q=80&w=2670&auto=format&fit=crop',
    ],
    bodyType: 'Sedan',
    engine: 'Dual electric motors',
    seats: 4,
    driveType: 'All-Wheel Drive',
    color: 'Carrara White',
    condition: 'New Arrival',
    availability: 'Reserved',
    location: 'Nairobi Showroom',
    vin: 'WP0AA2Y12RSA00123',
    negotiable: false,
    featured: true,
    loanEligible: true,
    description: 'Near-new electric performance sedan with rapid acceleration, premium build quality, and everyday usability.',
    features: ['Performance Battery Plus', 'Sport Chrono Package', 'Porsche Electric Sport Sound', 'Matrix LED', 'Adaptive Cruise', 'Apple CarPlay'],
    createdAt: now,
  },
  {
    id: 'v-004',
    slug: 'lexus-lx-600-2023',
    make: 'Lexus',
    model: 'LX',
    trim: '600',
    year: 2023,
    price: 22000000,
    mileage: 18000,
    fuel: 'Petrol',
    transmission: '10-Speed Automatic',
    image: 'https://images.unsplash.com/photo-1606014264388-75704179e961?q=80&w=2670&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1606014264388-75704179e961?q=80&w=2670&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1626668893632-6f3a4466d22f?q=80&w=2670&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1616422285623-13ff0162193c?q=80&w=2670&auto=format&fit=crop',
    ],
    bodyType: 'SUV',
    engine: '3.5L twin-turbo V6',
    seats: 7,
    driveType: 'Four-Wheel Drive',
    color: 'Sonic Titanium',
    condition: 'Foreign Used',
    availability: 'Available',
    location: 'Mombasa Partner Yard',
    vin: 'JTJGB7CX9P4001234',
    negotiable: true,
    featured: false,
    loanEligible: true,
    description: 'Full-size luxury SUV with serious off-road ability, premium interior technology, and strong resale reputation.',
    features: ['Mark Levinson Reference 3D', 'Dual-Screen Infotainment', 'Multi-Terrain Select', 'Cool Box', 'Leather Seats', 'Rear Entertainment'],
    createdAt: now,
  },
  {
    id: 'v-005',
    slug: 'bmw-x7-m60i-2024',
    make: 'BMW',
    model: 'X7',
    trim: 'M60i',
    year: 2024,
    price: 19800000,
    mileage: 4500,
    fuel: 'Petrol Mild-Hybrid',
    transmission: '8-Speed Sport Automatic',
    image: 'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?q=80&w=2670&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?q=80&w=2670&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?q=80&w=2670&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=2670&auto=format&fit=crop',
    ],
    bodyType: 'SUV',
    engine: '4.4L V8 mild hybrid',
    seats: 7,
    driveType: 'All-Wheel Drive',
    color: 'Brooklyn Grey',
    condition: 'Foreign Used',
    availability: 'Available',
    location: 'Nairobi Showroom',
    vin: '5UX33EM06R9001234',
    negotiable: true,
    featured: true,
    loanEligible: true,
    description: 'High-performance family SUV with luxury seating, strong road presence, and advanced driver assistance.',
    features: ['Bowers & Wilkins Diamond Surround', 'Sky Lounge Panoramic Roof', 'Integral Active Steering', 'M Sport Exhaust', 'Massage Seats', 'Laserlight'],
    createdAt: now,
  },
  {
    id: 'v-006',
    slug: 'audi-rs-q8-2022',
    make: 'Audi',
    model: 'RS Q8',
    year: 2022,
    price: 17500000,
    mileage: 32000,
    fuel: 'Petrol',
    transmission: '8-Speed Tiptronic',
    image: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=2669&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=2669&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?q=80&w=2670&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1603386329225-868f9b1ee6c9?q=80&w=2670&auto=format&fit=crop',
    ],
    bodyType: 'SUV',
    engine: '4.0L twin-turbo V8',
    seats: 5,
    driveType: 'Quattro All-Wheel Drive',
    color: 'Daytona Grey',
    condition: 'Foreign Used',
    availability: 'Available',
    location: 'Nairobi Showroom',
    vin: 'WU1ARBF14ND001234',
    negotiable: true,
    featured: false,
    loanEligible: true,
    description: 'Performance SUV with supercar pace, quattro traction, and a refined cabin suitable for daily executive use.',
    features: ['RS Sport Suspension Plus', 'Bang & Olufsen 3D Advanced', 'Valcona Leather', 'Carbon Optics', 'Adaptive Cruise', 'Head-Up Display'],
    createdAt: now,
  },
];

export const LOAN_TIERS: LoanTier[] = [
  {
    id: 'tier-logbook',
    title: 'Logbook Financing',
    description: "Unlock up to 70% of your vehicle's value while you continue to drive it. Applications are reviewed quickly by the Kiriro finance team.",
    maxLTV: 70,
    minAmount: 100000,
    maxAmount: 5000000,
    processingTime: 'Same-day review',
  },
  {
    id: 'tier-land',
    title: 'Land Title Financing',
    description: 'Leverage your real estate assets for structured credit lines designed for larger capital needs.',
    maxLTV: 50,
    minAmount: 1000000,
    maxAmount: 20000000,
    processingTime: '48-hour review',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    name: 'Mercy W.',
    role: 'Business owner',
    quote: 'Kiriro helped me secure a clean SUV and structure the repayment around my business cash flow.',
    result: 'Vehicle financed in one visit',
  },
  {
    name: 'Brian K.',
    role: 'Logistics operator',
    quote: 'The logbook loan process was clear, professional, and much faster than the bank options I had tried.',
    result: 'Working capital released',
  },
  {
    name: 'Amina S.',
    role: 'Property investor',
    quote: 'The team explained every document needed for land title financing and kept me updated throughout.',
    result: 'Property-backed facility reviewed',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'how-to-buy-a-premium-car-in-kenya',
    title: 'How to Buy a Premium Car in Kenya Without Regret',
    category: 'Car Buying Guides',
    excerpt: 'A practical checklist for mileage, import documents, inspection, valuation, and financing before you commit.',
    readTime: '6 min read',
    date: '2026-06-03',
  },
  {
    slug: 'logbook-loans-explained',
    title: 'Logbook Loans Explained: What Vehicle Owners Should Know',
    category: 'Logbook Loan Advice',
    excerpt: 'Understand loan-to-value, repayment terms, ownership requirements, and document preparation.',
    readTime: '5 min read',
    date: '2026-05-28',
  },
  {
    slug: 'land-title-financing-documents',
    title: 'Documents Needed For Land Title Financing',
    category: 'Property Financing',
    excerpt: 'A clear guide to title deed checks, valuation reports, ID, KRA PIN, and supporting financial records.',
    readTime: '4 min read',
    date: '2026-05-21',
  },
  {
    slug: 'vehicle-finance-monthly-estimates',
    title: 'How Vehicle Finance Monthly Estimates Work',
    category: 'Vehicle Financing Tips',
    excerpt: 'Learn how deposit, duration, principal, and interest assumptions affect monthly payments.',
    readTime: '7 min read',
    date: '2026-05-12',
  },
];

export const BRANCHES: Branch[] = [
  {
    name: 'Nairobi Showroom',
    location: 'Mombasa Road, Nairobi',
    phone: '+254 700 000 000',
    email: 'sales@kiriromotors.co.ke',
    hours: 'Mon - Sat, 8:30 AM - 6:00 PM',
  },
  {
    name: 'Finance Desk',
    location: 'Nairobi CBD appointments',
    phone: '+254 711 000 000',
    email: 'finance@kiriromotors.co.ke',
    hours: 'Mon - Fri, 9:00 AM - 5:00 PM',
  },
];

export const LOAN_PROCESS = [
  'Choose vehicle, logbook, or land title financing',
  'Submit applicant and asset details',
  'Upload required documents',
  'Finance team reviews and verifies',
  'Receive approval decision and next steps',
];

export const WHATSAPP_NUMBER = '254700000000';
